version: "3.9"

services:
  recording:
    container_name: chime-recording
    # image: chime-recording:latest
    build:
      context: .
      # dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MEETING_URL: ${MEETING_URL}
      RECORDING_ARTIFACTS_BUCKET: ${RECORDING_ARTIFACTS_BUCKET}
